--- 
framework: 
  AdminMode: 1
  ApplicationClass: TestSimple
  ApplicationName: TestSimple
  ApplicationUUID: 7E80251C-196B-11DF-85A5-E9C9E75E0F70
  ConfigFileVersion: 4
  Database: 
    AutoUpgrade: 1
    CheckSchema: 1
    Database: testsimple
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - Markapl: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestSimple::View
  View: 
    Handlers: 
      - Jifty::View::Static::Handler
      - JiftyX::Markapl::Handler
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
